# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('hearts', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('flags', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('hearts', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('flags', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerCommentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('usage', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('hearts', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('flags', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(max_length=200)),
                ('closed', models.BooleanField(default=False)),
                ('answers', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('hearts', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('flags', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionCommentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerCommentFlag',
            fields=[
                ('answercommentpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.AnswerCommentPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Flags -> Answer Comment',
            },
            bases=('alpha.answercommentpoint',),
        ),
        migrations.CreateModel(
            name='AnswerCommentHeart',
            fields=[
                ('answercommentpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.AnswerCommentPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Hearts -> Answer Comment',
            },
            bases=('alpha.answercommentpoint',),
        ),
        migrations.CreateModel(
            name='AnswerFlag',
            fields=[
                ('answerpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.AnswerPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Flags -> Answer',
            },
            bases=('alpha.answerpoint',),
        ),
        migrations.CreateModel(
            name='AnswerHeart',
            fields=[
                ('answerpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.AnswerPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Hearts -> Answer',
            },
            bases=('alpha.answerpoint',),
        ),
        migrations.CreateModel(
            name='QuestionCommentFlag',
            fields=[
                ('questioncommentpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.QuestionCommentPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Flags -> Question Comment',
            },
            bases=('alpha.questioncommentpoint',),
        ),
        migrations.CreateModel(
            name='QuestionCommentHeart',
            fields=[
                ('questioncommentpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.QuestionCommentPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Hearts -> Question Comment',
            },
            bases=('alpha.questioncommentpoint',),
        ),
        migrations.CreateModel(
            name='QuestionFlag',
            fields=[
                ('questionpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.QuestionPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Flags -> Question',
            },
            bases=('alpha.questionpoint',),
        ),
        migrations.CreateModel(
            name='QuestionHeart',
            fields=[
                ('questionpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.QuestionPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Hearts -> Question',
            },
            bases=('alpha.questionpoint',),
        ),
        migrations.AddField(
            model_name='questionpoint',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Question'),
        ),
        migrations.AddField(
            model_name='questionpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questioncommentpoint',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.QuestionComment'),
        ),
        migrations.AddField(
            model_name='questioncommentpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerpoint',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Answer'),
        ),
        migrations.AddField(
            model_name='answerpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answercommentpoint',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.AnswerComment'),
        ),
        migrations.AddField(
            model_name='answercommentpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Question'),
        ),
    ]
