# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='followers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
