# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_question_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFollowers',
            fields=[
                ('questionpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alpha.QuestionPoint')),
            ],
            options={
                'verbose_name_plural': 'X: Follows -> Question',
            },
            bases=('alpha.questionpoint',),
        ),
    ]
