# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_questionfollowers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='frm',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='to',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('A', 'wrote an answer to your question.'), ('QC', 'commented on your question.'), ('AC', 'commented on your answer.'), ('QH', 'liked your answer.'), ('AH', 'liked your answer.')], max_length=2),
        ),
    ]
