# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alpha', '0004_auto_20160324_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCommentFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.QuestionComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'X: Flags -> Question Comment',
            },
        ),
        migrations.CreateModel(
            name='QuestionCommentHeart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.QuestionComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'X: Hearts -> Question Comment',
            },
        ),
        migrations.AlterModelOptions(
            name='answerflag',
            options={'verbose_name_plural': 'X: Flags -> Answer'},
        ),
        migrations.AlterModelOptions(
            name='answerheart',
            options={'verbose_name_plural': 'X: Hearts -> Answer'},
        ),
        migrations.AlterModelOptions(
            name='questionflag',
            options={'verbose_name_plural': 'X: Flags -> Question'},
        ),
        migrations.AlterModelOptions(
            name='questionheart',
            options={'verbose_name_plural': 'X: Hearts -> Question'},
        ),
        migrations.AlterUniqueTogether(
            name='questioncommentheart',
            unique_together=set([('comment', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='questioncommentflag',
            unique_together=set([('comment', 'user')]),
        ),
    ]
