# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_auto_20160519_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationobject',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='notificationobject',
            unique_together=set([]),
        ),
    ]
