# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0005_auto_20160518_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
